/**
 * Machine Knitter's Bookshelf — data access layer.
 *
 * This module is the single source of truth for reading bookshelf data and is
 * intentionally the seam for future expansion. The reference catalog is static
 * (generated by scripts/import-bookshelf.cjs into src/data/bookshelf.json), but
 * member-specific data ("In My Library") and ratings are expected to move to
 * Memberstack custom fields or Supabase later.
 *
 * When that happens, only this file (and the LibraryStore client module) needs
 * to change — pages and components consume these helpers, not the JSON.
 */
import booksData from "../data/bookshelf.json";

export interface Book {
  /** Stable identifier (legacy BookID). Used in the detail route /reference/bookshelf/{id}. */
  id: string;
  title: string;
  author: string;
  /** Not present in the source CSV yet; reserved for future data. */
  year: string | null;
  topic: string;
  /** Original description markup (may contain limited HTML such as <br> and links). */
  description: string;
  /** Plain-text description for search indexing and card previews. */
  descriptionText: string;
  /** Public path, e.g. /images/books/foo.jpg (same value as `image`). */
  thumbnail: string;
  image: string;
  /** Optional informational outbound link (where the book can be found). */
  url: string;
  tags: string[];
  avgRating: number;
  ratingCount: number;
}

const books: Book[] = booksData as Book[];

export function getAllBooks(): Book[] {
  return books;
}

export function getBookById(id: string | undefined): Book | undefined {
  if (!id) return undefined;
  return books.find((b) => b.id === id);
}

/** Unique, sorted list of non-empty topics found in the data. */
export function getAllTopics(): string[] {
  const set = new Set<string>();
  for (const b of books) {
    const t = b.topic?.trim();
    if (t) set.add(t);
  }
  return Array.from(set).sort((a, b) => a.localeCompare(b, "en", { sensitivity: "base" }));
}

/** Unique, sorted list of tags found in the data (case-insensitive de-dupe). */
export function getAllTags(): string[] {
  const map = new Map<string, string>();
  for (const b of books) {
    for (const raw of b.tags || []) {
      const tag = raw.trim();
      if (!tag) continue;
      const key = tag.toLowerCase();
      if (!map.has(key)) map.set(key, tag);
    }
  }
  return Array.from(map.values()).sort((a, b) =>
    a.localeCompare(b, "en", { sensitivity: "base" })
  );
}

/** Whether a book has any usable rating data. */
export function hasRating(book: Book): boolean {
  return book.ratingCount > 0 && book.avgRating > 0;
}

/** Combined lowercase string used for instant client-side search matching. */
export function buildSearchIndex(book: Book): string {
  return [book.title, book.author, book.topic, book.tags.join(" "), book.descriptionText]
    .join(" ")
    .toLowerCase();
}
