import type { LegacyTableDef } from "./types";

const ts = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "text" as const, nullable: true });

const tsReq = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "text" as const, nullable: false });

const int = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "integer" as const, nullable: true });

const intReq = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "integer" as const, nullable: false });

const bigintReq = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "bigint" as const, nullable: false });

const numeric = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "numeric" as const, nullable: true });

const timestamptz = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "timestamptz" as const, nullable: true });

const date = (source: string, pg = source.toLowerCase()) =>
  ({ source, pg, type: "date" as const, nullable: true });

/** Approved legacy export tables and Postgres mappings (from 2026-07-11 CSV inspection). */
export const LEGACY_TABLE_DEFINITIONS: LegacyTableDef[] = [
  {
    exportName: "Members",
    pgTable: "legacy_members",
    primaryKey: ["memberid"],
    required: true,
    columns: [
      tsReq("memberid"),
      ts("Fristname", "fristname"),
      ts("Lastname", "lastname"),
      ts("Email", "email"),
      timestamptz("DateJoined", "datejoined"),
      int("active"),
      int("betaactive"),
      ts("Address", "address"),
      ts("Address2", "address2"),
      ts("City", "city"),
      ts("State", "state"),
      ts("PostalCode", "postalcode"),
      ts("Country", "country"),
      date("BirthDayInfo", "birthdayinfo"),
      ts("Notes", "notes"),
      int("UnSubscribed", "unsubscribed"),
      timestamptz("UnSubscribedDate", "unsubscribeddate"),
      ts("MailChimpID", "mailchimpid"),
      int("MailchimpActive", "mailchimpactive"),
      ts("MailchimpStatus", "mailchimpstatus"),
      ts("ActiveCampaignID", "activecampaignid"),
      ts("ActiveCampaignStatus", "activecampaignstatus"),
      ts("ForumUserId", "forumuserid"),
      ts("HeartbeatID", "heartbeatid"),
      int("CurrentSubscriber", "currentsubscriber"),
      timestamptz("SubscriptionDate", "subscriptiondate"),
      timestamptz("SubscriptionExpiring", "subscriptionexpiring"),
      ts("SubscriptionType", "subscriptiontype"),
      int("SubscriptionRenewal", "subscriptionrenewal"),
      int("MonthlySubscriber", "monthlysubscriber"),
      int("SubscriptionID_FK", "subscriptionid_fk"),
      ts("StripCustomerID", "stripcustomerid"),
    ],
  },
  {
    exportName: "Subscriptions",
    pgTable: "legacy_subscriptions",
    primaryKey: ["subscriptionid"],
    required: true,
    columns: [
      bigintReq("subscriptionID", "subscriptionid"),
      tsReq("Memberid_FK", "memberid_fk"),
      timestamptz("Datebought", "datebought"),
      timestamptz("ExpirationDate", "expirationdate"),
      ts("transactionguid_fk"),
      numeric("Dollaramount", "dollaramount"),
      ts("ARB_ID", "arb_id"),
      ts("ABR_InoviceNumber", "abr_inovicenumber"),
      ts("Monthlypaymentwddx"),
      int("renewal"),
      int("MonthlyBilling", "monthlybilling"),
      ts("MonthlyYearCompletedate", "monthlyyearcompletedate"),
      int("Cancelled", "cancelled"),
      timestamptz("CancelDate", "canceldate"),
      ts("CardYear", "cardyear"),
      ts("CardMonth", "cardmonth"),
      ts("CardLast4", "cardlast4"),
      int("IssueWithSub", "issuewithsub"),
      timestamptz("IssueDate", "issuedate"),
      int("Evidence", "evidence"),
      int("Premium", "premium"),
      ts("Processor", "processor"),
      ts("SubscriptionRate_ID", "subscriptionrate_id"),
    ],
  },
  {
    exportName: "Store_Transactions",
    pgTable: "legacy_store_transactions",
    primaryKey: ["storetransactionid"],
    required: true,
    columns: [
      bigintReq("StoreTransactionID", "storetransactionid"),
      tsReq("TransactionID", "transactionid"),
      tsReq("memberid_fk"),
      ts("Billing_FirstName", "billing_firstname"),
      ts("Billing_LastName", "billing_lastname"),
      ts("Billing_address", "billing_address"),
      ts("Billing_address2", "billing_address2"),
      ts("Billing_city", "billing_city"),
      ts("Billing_state", "billing_state"),
      ts("Billing_Zipcode", "billing_zipcode"),
      ts("Billing_phone", "billing_phone"),
      ts("Billing_email", "billing_email"),
      ts("Billing_Country", "billing_country"),
      timestamptz("PurchaseDate", "purchasedate"),
      ts("Shipping_FirstName", "shipping_firstname"),
      ts("Shipping_LastName", "shipping_lastname"),
      ts("Shipping_address", "shipping_address"),
      ts("Shipping_Address2", "shipping_address2"),
      ts("Shipping_City", "shipping_city"),
      ts("Shipping_state", "shipping_state"),
      ts("Shipping_Zipcode", "shipping_zipcode"),
      ts("Shipping_Country", "shipping_country"),
      ts("Shipping_phone", "shipping_phone"),
      numeric("ItemCost", "itemcost"),
      numeric("Shippingcost", "shippingcost"),
      numeric("SalesTax", "salestax"),
      numeric("TotalCost", "totalcost"),
      ts("AthorizeId", "athorizeid"),
      ts("AdditionalNotes", "additionalnotes"),
      ts("TransactionMethod", "transactionmethod"),
      int("Paid", "paid"),
      int("Coupon_FK", "coupon_fk"),
      numeric("Discount", "discount"),
      ts("internalnotes"),
      ts("Fulfillment_id", "fulfillment_id"),
      ts("Fulfillment_status", "fulfillment_status"),
      ts("Fulfillment_Ordernumber", "fulfillment_ordernumber"),
      int("Fulfillment_hide", "fulfillment_hide"),
      numeric("Fulfillment_Shipping_cost", "fulfillment_shipping_cost"),
      ts("Fulfillment_OrderConfirmation", "fulfillment_orderconfirmation"),
      ts("Fulfillment_status_current", "fulfillment_status_current"),
      int("Efill_completed_order", "efill_completed_order"),
      ts("OrderInfo", "orderinfo"),
      ts("VendorNotes", "vendornotes"),
    ],
  },
  {
    exportName: "Store_Transactions_items",
    pgTable: "legacy_store_transaction_items",
    primaryKey: ["transaction_itemid"],
    required: true,
    columns: [
      bigintReq("Transaction_itemid", "transaction_itemid"),
      bigintReq("StoreTransactionID", "storetransactionid"),
      int("itemid"),
      ts("ItemName", "itemname"),
      ts("Color", "color"),
      int("Quantity", "quantity"),
      int("VendorID", "vendorid"),
      numeric("PricePerItem", "priceperitem"),
      numeric("TotalPrice", "totalprice"),
      ts("SaleDescripton", "saledescripton"),
      ts("perlable"),
      ts("product"),
      numeric("weight"),
      int("OnSale", "onsale"),
      ts("Putup", "putup"),
      int("ConfirmedRecipt", "confirmedrecipt"),
      timestamptz("ShippingDate", "shippingdate"),
      ts("TrackingNumber", "trackingnumber"),
      int("Shipped", "shipped"),
      ts("carrier"),
      int("VendorPaid", "vendorpaid"),
      timestamptz("orderdate"),
      ts("ColorId", "colorid"),
      ts("PONumber", "ponumber"),
      int("backorder"),
      int("RemoveFromList", "removefromlist"),
      numeric("Deposit", "deposit"),
      ts("VendorInvoice", "vendorinvoice"),
      timestamptz("VendorPaidDate", "vendorpaiddate"),
    ],
  },
  {
    exportName: "HomeStudy_Course_member_library",
    pgTable: "legacy_course_member_library",
    primaryKey: ["homestudy_libraryid"],
    required: true,
    columns: [
      bigintReq("Homestudy_libraryid", "homestudy_libraryid"),
      intReq("HomeStudy_courseid_fk", "homestudy_courseid_fk"),
      timestamptz("Dateadded", "dateadded"),
      int("Credit_id_fk", "credit_id_fk"),
      tsReq("memberid_fk"),
      int("Subscriberfree", "subscriberfree"),
    ],
  },
  {
    exportName: "Member_pattern_details",
    pgTable: "legacy_member_pattern_details",
    primaryKey: ["detailid"],
    required: true,
    columns: [
      tsReq("member_fk"),
      bigintReq("detailID", "detailid"),
      ts("garmentID_FK", "garmentid_fk"),
      timestamptz("builddate"),
      ts("Libraryid_fk", "libraryid_fk"),
      ts("buildnotes"),
      ts("buildid"),
      ts("size"),
      ts("patterntype"),
      ts("GaugeSizing", "gaugesizing"),
      ts("ChallengeID_fk", "challengeid_fk"),
      ts("ChallengePatternName", "challengepatternname"),
      int("customfit"),
      ts("CustomName", "customname"),
      ts("SizingSizeID", "sizingsizeid"),
      int("IssueWithPattern", "issuewithpattern"),
      int("IssueWithPatternMarker", "issuewithpatternmarker"),
      ts("NeckShape", "neckshape"),
      ts("GarmentStyle", "garmentstyle"),
      ts("datatoggles"),
      ts("PatternIdList", "patternidlist"),
      int("fixed"),
    ],
  },
  {
    exportName: "Pattern_Library",
    pgTable: "legacy_pattern_library",
    primaryKey: ["patternlibarry_id"],
    required: true,
    columns: [
      bigintReq("PatternLibarry_id", "patternlibarry_id"),
      ts("Title", "title"),
      ts("description"),
      ts("keywords"),
      int("GarmentID_fk", "garmentid_fk"),
      int("Authorid_fk", "authorid_fk"),
      int("designerid_fk"),
      int("skill_level_id"),
      ts("PatternType", "patterntype"),
      int("CategoryId", "categoryid"),
      ts("Filename", "filename"),
      numeric("cost"),
      int("active"),
      timestamptz("dateadded"),
      int("freewithsubscription"),
      int("Credits", "credits"),
      int("SizingTypeid_FK", "sizingtypeid_fk"),
      ts("AdditionalImages", "additionalimages"),
      int("AddCopyWrite", "addcopywrite"),
      numeric("NetCost", "netcost"),
    ],
  },
  {
    exportName: "Pattern_Library_purchases",
    pgTable: "legacy_pattern_library_purchases",
    primaryKey: ["pattern_library_purchases"],
    required: true,
    columns: [
      bigintReq("Pattern_library_purchases", "pattern_library_purchases"),
      tsReq("transactionguid"),
      timestamptz("dateadded"),
      tsReq("Memberid_FK", "memberid_fk"),
      bigintReq("PatternLibarry_id", "patternlibarry_id"),
      int("VendorPaid", "vendorpaid"),
    ],
  },
];

export const LEGACY_TABLE_LOAD_ORDER = [
  "legacy_members",
  "legacy_pattern_library",
  "legacy_subscriptions",
  "legacy_store_transactions",
  "legacy_store_transaction_items",
  "legacy_course_member_library",
  "legacy_member_pattern_details",
  "legacy_pattern_library_purchases",
] as const;

export function getLegacyTableDefByPgTable(pgTable: string): LegacyTableDef | undefined {
  return LEGACY_TABLE_DEFINITIONS.find((def) => def.pgTable === pgTable);
}

export function getLegacyTableDefByExportName(exportName: string): LegacyTableDef | undefined {
  return LEGACY_TABLE_DEFINITIONS.find((def) => def.exportName === exportName);
}
