import {
  getAccordionLayoutParts,
  isAccordionLayoutBlock,
} from "./courseAccordionLayout";
import {
  TEXT_IMAGE_LAYOUT_TYPE,
  TEXT_VIDEO_LAYOUT_TYPE,
  THREE_VIDEOS_LAYOUT_TYPE,
  type FlatContentItem,
} from "./courseContentEditorTypes";
import {
  getLayoutHeader,
  getTextImageLayoutParts,
  isTextImageLayoutBlock,
} from "./courseTextImageLayout";
import {
  getTextVideoLayoutParts,
  isTextVideoLayoutBlock,
} from "./courseTextVideoLayout";
import {
  getThreeVideosLayoutParts,
  isThreeVideosLayoutBlock,
} from "./courseThreeVideosLayout";
import type { CourseBlock, CourseLesson, CoursePreviewData } from "./coursePreviewPoc";
import { sortedBlocks, sortedComponents } from "./coursePreviewPoc";
import { slugify } from "../slugify";

export type { FlatContentItem };

/** Block slugs generated at import time (not human-readable section names). */
export const AUTO_GENERATED_BLOCK_SLUG_RE =
  /^(text-image|text-video|three-videos)-\d+$/;

export type LessonContentItemRef = FlatContentItem & {
  itemSlug: string;
};

export type LessonContentNavEntry = {
  blockSlug: string;
  itemSlug: string;
  title: string;
  legacyComponentId: number;
  oneBasedIndex: number;
};

export type CourseContentItemStep = {
  lesson: CourseLesson;
  item: LessonContentItemRef;
};

const ITEM_TYPE_NAV_LABELS: Record<string, string> = {
  richText: "Text",
  video: "Video",
  download: "Download",
  image: "Image",
  imageGallery: "Gallery",
  imageCarousel: "Carousel",
  exerciseAccordion: "Accordion",
  embeddedTool: "Tool",
  migrationPending: "Pending",
  [TEXT_VIDEO_LAYOUT_TYPE]: "Text + Video",
  [TEXT_IMAGE_LAYOUT_TYPE]: "Text + Image",
  [THREE_VIDEOS_LAYOUT_TYPE]: "Three Videos",
};

function blockTitleForEditing(title: unknown): string {
  const trimmed = typeof title === "string" ? title.trim() : "";
  if (!trimmed || /^\(untitled assign \d+\)$/i.test(trimmed)) return "";
  return trimmed;
}

export function isAutoGeneratedBlockSlug(blockSlug: string): boolean {
  return AUTO_GENERATED_BLOCK_SLUG_RE.test(blockSlug.trim());
}

export function preferredPublicItemSlug(
  blockSlug: string,
  displayTitle: string,
): string {
  if (displayTitle && isAutoGeneratedBlockSlug(blockSlug)) {
    const fromTitle = slugify(displayTitle);
    if (fromTitle) return fromTitle;
  }
  return blockSlug.trim();
}

function ensureUniqueSlug(base: string, used: Set<string>): string {
  const normalized = base.trim();
  if (!normalized) {
    return ensureUniqueSlug("untitled-section", used);
  }
  if (!used.has(normalized)) return normalized;
  let suffix = 2;
  while (used.has(`${normalized}--${suffix}`)) {
    suffix += 1;
  }
  return `${normalized}--${suffix}`;
}

export function findBlockBySlug(
  lesson: CourseLesson,
  blockSlug: string,
): CourseBlock | undefined {
  return sortedBlocks(lesson).find((block) => block.slug === blockSlug);
}

/** Block heading shown in the admin editor item list. */
export function contentItemBlockTitle(
  lesson: CourseLesson,
  blockSlug: string,
): string {
  const block = findBlockBySlug(lesson, blockSlug);
  if (!block) return "";
  return blockTitleForEditing(block.title);
}

/** Public-facing heading for a flattened content item (matches admin sidebar items). */
export function contentItemDisplayTitle(
  lesson: CourseLesson,
  item: FlatContentItem,
): string {
  const block = findBlockBySlug(lesson, item.blockSlug);
  if (!block) return "";

  if (item.type === TEXT_IMAGE_LAYOUT_TYPE) {
    const header = getLayoutHeader(block);
    if (header?.trim()) return header.trim();
  }

  return blockTitleForEditing(block.title);
}

/** Sidebar label — disambiguates multiple items that share a block title. */
export function contentItemNavTitle(
  lesson: CourseLesson,
  item: FlatContentItem,
  items: FlatContentItem[],
): string {
  const title = contentItemDisplayTitle(lesson, item) || "Untitled Section";
  const blockSiblings = items.filter((entry) => entry.blockSlug === item.blockSlug);
  if (blockSiblings.length <= 1) return title;

  const typeLabel = ITEM_TYPE_NAV_LABELS[item.type] ?? item.type;
  return `${title} (${typeLabel})`;
}

/** @deprecated Use itemSlug on LessonContentNavEntry instead of in-page anchors. */
export function contentItemAnchorId(
  lessonSlug: string,
  item: FlatContentItem,
): string {
  return `${lessonSlug}--${item.blockSlug}--${item.legacyComponentId}`;
}

function allocateItemSlug(
  lesson: CourseLesson,
  item: FlatContentItem,
  items: FlatContentItem[],
  used: Set<string>,
): string {
  const title = contentItemDisplayTitle(lesson, item);
  const blockSiblings = items.filter((entry) => entry.blockSlug === item.blockSlug);
  const blockIndex = blockSiblings.findIndex(
    (entry) =>
      entry.legacyComponentId === item.legacyComponentId && entry.type === item.type,
  );

  let base: string;
  if (blockSiblings.length === 1) {
    base = preferredPublicItemSlug(item.blockSlug, title);
  } else if (blockIndex === 0) {
    base = preferredPublicItemSlug(item.blockSlug, title);
  } else {
    base = `${preferredPublicItemSlug(item.blockSlug, title)}--${item.legacyComponentId}`;
  }

  return ensureUniqueSlug(base, used);
}

/**
 * Ordered lesson content items — same sequence as /admin/course-content.
 * One item per component, except composite layout blocks (text+video, etc.).
 */
export function flattenLessonContent(lesson: CourseLesson): FlatContentItem[] {
  const items: FlatContentItem[] = [];

  for (const block of sortedBlocks(lesson)) {
    if (isTextVideoLayoutBlock(block)) {
      const parts = getTextVideoLayoutParts(block);
      if (!parts) continue;
      items.push({
        blockSlug: String(block.slug ?? ""),
        legacyComponentId: Number(parts.leftText.legacyComponentId),
        type: TEXT_VIDEO_LAYOUT_TYPE,
        pairedLegacyComponentId: Number(parts.video.legacyComponentId),
        component: {
          type: TEXT_VIDEO_LAYOUT_TYPE,
          leftText: parts.leftText,
          video: parts.video,
          bottomText: parts.bottomText,
          richText: parts.leftText,
        },
      });
      continue;
    }

    if (isThreeVideosLayoutBlock(block)) {
      const parts = getThreeVideosLayoutParts(block);
      if (!parts) continue;
      items.push({
        blockSlug: String(block.slug ?? ""),
        legacyComponentId: Number(
          parts.intro?.legacyComponentId ?? parts.slots[0]!.video.legacyComponentId,
        ),
        type: THREE_VIDEOS_LAYOUT_TYPE,
        component: {
          type: THREE_VIDEOS_LAYOUT_TYPE,
          intro: parts.intro,
          slots: parts.slots,
          outro: parts.outro,
        },
      });
      continue;
    }

    if (isTextImageLayoutBlock(block)) {
      const parts = getTextImageLayoutParts(block);
      if (!parts) continue;
      items.push({
        blockSlug: String(block.slug ?? ""),
        legacyComponentId: Number(parts.text.legacyComponentId),
        type: TEXT_IMAGE_LAYOUT_TYPE,
        pairedLegacyComponentId: Number(parts.image.legacyComponentId),
        component: {
          type: TEXT_IMAGE_LAYOUT_TYPE,
          text: parts.text,
          image: parts.image,
          imagePosition: block.layoutOptions?.imagePosition ?? "right",
          header: getLayoutHeader(block),
        },
      });
      continue;
    }

    if (isAccordionLayoutBlock(block)) {
      const parts = getAccordionLayoutParts(block);
      if (!parts) continue;
      items.push({
        blockSlug: String(block.slug ?? ""),
        legacyComponentId: Number(parts.accordion.legacyComponentId),
        type: "exerciseAccordion",
        introLegacyComponentId: parts.introText
          ? Number(parts.introText.legacyComponentId)
          : undefined,
        component: {
          ...(parts.accordion as Record<string, unknown>),
          introText: parts.introText,
        },
      });
      continue;
    }

    for (const component of sortedComponents(block)) {
      items.push({
        blockSlug: String(block.slug ?? ""),
        legacyComponentId: Number(component.legacyComponentId),
        type: String(component.type ?? ""),
        component: component as Record<string, unknown>,
      });
    }
  }

  return items;
}

/** Flattened items with stable URL slugs unique within the lesson. */
export function getLessonContentItemsWithSlugs(
  lesson: CourseLesson,
): LessonContentItemRef[] {
  const items = flattenLessonContent(lesson);
  const used = new Set<string>();

  return items.map((item) => ({
    ...item,
    itemSlug: allocateItemSlug(lesson, item, items, used),
  }));
}

export function findLessonContentItemBySlug(
  lesson: CourseLesson,
  itemSlug: string,
): LessonContentItemRef | undefined {
  return getLessonContentItemsWithSlugs(lesson).find(
    (item) => item.itemSlug === itemSlug.trim(),
  );
}

function contentItemMatchesRef(
  item: FlatContentItem,
  ref: Pick<FlatContentItem, "blockSlug" | "legacyComponentId" | "type">,
): boolean {
  if (
    ref.type === TEXT_VIDEO_LAYOUT_TYPE ||
    item.type === TEXT_VIDEO_LAYOUT_TYPE ||
    ref.type === TEXT_IMAGE_LAYOUT_TYPE ||
    item.type === TEXT_IMAGE_LAYOUT_TYPE ||
    ref.type === THREE_VIDEOS_LAYOUT_TYPE ||
    item.type === THREE_VIDEOS_LAYOUT_TYPE
  ) {
    return ref.blockSlug === item.blockSlug && ref.type === item.type;
  }
  return (
    ref.blockSlug === item.blockSlug &&
    ref.legacyComponentId === item.legacyComponentId &&
    ref.type === item.type
  );
}

/** Resolve the public item slug for an admin editor selection. */
export function findLessonContentItemSlugForRef(
  lesson: CourseLesson,
  ref: Pick<FlatContentItem, "blockSlug" | "legacyComponentId" | "type"> | null,
): string | null {
  if (!ref) return null;
  const match = getLessonContentItemsWithSlugs(lesson).find((item) =>
    contentItemMatchesRef(item, ref),
  );
  return match?.itemSlug ?? null;
}

/** Sidebar nav — one link per flattened item, in admin order. */
export function getLessonContentNavEntries(
  lesson: CourseLesson,
): LessonContentNavEntry[] {
  const flatItems = flattenLessonContent(lesson);

  return getLessonContentItemsWithSlugs(lesson).map((item, index) => ({
    blockSlug: item.blockSlug,
    itemSlug: item.itemSlug,
    title: contentItemNavTitle(lesson, item, flatItems),
    legacyComponentId: item.legacyComponentId,
    oneBasedIndex: index + 1,
  }));
}

export function getCourseContentItemSequence(
  course: CoursePreviewData,
): CourseContentItemStep[] {
  const lessons = [...course.lessons].sort(
    (a, b) => a.displayOrder - b.displayOrder,
  );

  return lessons.flatMap((lesson) =>
    getLessonContentItemsWithSlugs(lesson).map((item) => ({ lesson, item })),
  );
}

export function getCourseContentItemNeighbors(
  course: CoursePreviewData,
  lessonSlug: string,
  itemSlug: string,
): {
  index: number;
  prev: CourseContentItemStep | null;
  next: CourseContentItemStep | null;
} {
  const sequence = getCourseContentItemSequence(course);
  const index = sequence.findIndex(
    (step) => step.lesson.slug === lessonSlug && step.item.itemSlug === itemSlug,
  );

  if (index < 0) {
    return { index: -1, prev: null, next: null };
  }

  return {
    index,
    prev: index > 0 ? sequence[index - 1]! : null,
    next: index < sequence.length - 1 ? sequence[index + 1]! : null,
  };
}

export function getFirstLessonContentItemSlug(lesson: CourseLesson): string | null {
  return getLessonContentItemsWithSlugs(lesson)[0]?.itemSlug ?? null;
}
