-- Advance help_hub_categories identity after explicit seed IDs 1–9.
-- Safe to re-run. Does not modify help_hub_tips.
-- Do not apply this migration to production from this change set.

BEGIN;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'help_hub_categories'
      AND column_name = 'id'
      AND is_identity = 'NO'
  ) THEN
    ALTER TABLE public.help_hub_categories
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
END $$;

SELECT setval(
  pg_get_serial_sequence('public.help_hub_categories', 'id'),
  GREATEST(COALESCE((SELECT MAX(id) FROM public.help_hub_categories), 9), 9)
)
WHERE pg_get_serial_sequence('public.help_hub_categories', 'id') IS NOT NULL;

COMMIT;
